# ------------------------------------------------
# @author Adrian Szczepanski
# @date 06-03-2022
# ------------------------------------------------

# Target
target := libBlinkLed-Core

# Directories
project_dir := ..
make_dir := $(project_dir)/make

# Sources 
cxx_sources :=  \
$(wildcard libBlinkLed/Core/*.cpp) \

# Includes
cxx_includes := \

# Defines
cxx_defs = \

# Append rest of Makefile from template
include $(make_dir)/SoftwareLib.mk